### PR TITLE
Fixed handling of \r

### LINKED ISSUE #58: Whitespace character handling
There is a discrepancy with how the JS library parses whitespace vs the PHP library.

```php
 $p  = new \JmesPath\Parser();
var_dump($p->parse("[]\r[]"));
array(3) {
  ["type"]=>
  string(10) "projection"
  ["from"]=>
  string(5) "array"
  ["children"]=>
  array(2) {
    [0]=>
    array(2) {
      ["type"]=>
      string(7) "flatten"
      ["children"]=>
      array(1) {
        [0]=>
        array(3) {
          ["type"]=>
          string(10) "projection"
          ["from"]=>
          string(5) "array"
          ["children"]=>
          array(2) {
            [0]=>
            array(2) {
              ["type"]=>
              string(7) "flatten"
              ["children"]=>
              array(1) {
                [0]=>
                array(1) {
                  ["type"]=>
                  string(7) "current"
                }
              }
            }
            [1]=>
            array(1) {
              ["type"]=>
              string(7) "current"
            }
          }
        }
      }
    }
    [1]=>
    array(1) {
      ["type"]=>
      string(7) "current"
    }
  }
}

```

```js
jmespath.compile("[]\r[]");
jmespath.js:309 Uncaught LexerError: Unknown character:
    at Lexer.tokenize (https://run.plnkr.co/preview/ck3fuluzv0006315wgzsg94tg/jmespath.js:307:31)
    at Parser._loadTokens (https://run.plnkr.co/preview/ck3fuluzv0006315wgzsg94tg/jmespath.js:523:30)
    at Parser.parse (https://run.plnkr.co/preview/ck3fuluzv0006315wgzsg94tg/jmespath.js:508:16)
    at Object.compile (https://run.plnkr.co/preview/ck3fuluzv0006315wgzsg94tg/jmespath.js:1647:22)
    at <anonymous>:1:10
```

It seems to me 1 of the implementations is wrong, not sure which.

### PR DESCRIPTION
**Pull request by SamMousa**
Fixes #58

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Looks good. I've added your tests to the PHP implementation, and it is passing on them (as expected).

**Comment by SamMousa** [comment]
Are you planning to maintain your fork? Or still hoping to get this merged here at some point?

**Comment by GrahamCampbell** [comment]
I'm not talking about my fork. I'm talking about https://github.com/jmespath/jmespath.php. :)

**Comment by GrahamCampbell** [comment]
By added, I should have said "it will be added in the next few minutes". I've not yet merged the changes. ;)

**Comment by SamMousa** [comment]
Ah, didn't see that correctly (and didn't realize you could merge into this repo :))

**Comment by GrahamCampbell** [comment]
I am helping maintain the PHP implementation only, at the moment. :)

**Pull request closed without merging**
